### ISSUE TITLE
.ascx error

### ISSUE THREAD

**Issue by kurtwilby** [weggetor/BBImageStory#1]
when adding module to page I get two error relating to view and settings .ascx file

**Comment by weggetor** [comment]
Hi Kurt - No idea how you get this installed! 

You only get this compiled correct in release mode if you have installed the latest http://dnntcmsbuild.codeplex.com/ and https://github.com/loresoft/msbuildtasks. After this and successful compilation in release mode you have to open the dnn manifest and change the endings of the view and quicksettings control to ".html" instead of ".ascx", because its a DNN SPA module. And when this is all successfully done you can install the module - but it needs additionally a whole bunch of Javascript libraries (AngularJS and others). 

Because all this is no easy task I added now an Install package which contains everything you need (see: https://github.com/weggetor/BBImageStory/releases/tag/v1.0.0). Hope that helps !

And please be aware: This module only runs in DNN 8!

**Comment by INNO-Software** [comment]
I'm curious, did you utilize the DNN8 templates for SPA? I've been using the MVC templates for DNN8 and placing your solution inside the MVC folder under DesktopModules is enough to make the Release mode build create your installation package for you. (Provided you adjusted your manifest file to reflect your own changes to the starter template.)

Although I could checkout _both_ of those projects it'd be encouraging to reduce the complexity a bit.

Forgive me if I've oversimplified here. I was just hoping to make it easier to possibly contribute. I used your installer to try it, but like the idea of adjusting and rebuilding it, etc. (And if I add something useful, to be able to submit it to you.)

Cheers!
