### ISSUE TITLE
new Story is always displayed

### ISSUE THREAD

**Issue by sleupold** [weggetor/BBImageStory#2]
I added a module to a page, created a new story and added images.
Story is displayed file.
I added another BBimageStory module to a different page and the original story is displayed here as well.

Checking Table BBImageStory_Story, neither PortalID nor ModuleID contain a value.
But the issue remains, even after populating these columns with proper values (i.e. there is an issue in  "Get.." call as well)

**Comment by sleupold** [comment]
there seem to be some issues in your data access, using @2 instead of @0 and inefficient queries (which might become an issue, if there are numerous stories in a DNN installation with many pictures).

**Comment by weggetor** [comment]
This was mainly a problem with timing between saving settings and page reload (save partitioning as modules scope but when page reloads this information is yet not available.) Solved by introducing a 500 ms wait cycle between save and page reload. Data access seems to be OK, @0 and @2 (and @1)  are used  but this is by design

**Comment by sleupold** [comment]
I tested and am able to confirm this to be fixed in latest version.
